<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Выберите персонажа 1</h1>
<select name="character" id="character">
    <option disabled selected>Выберите расу</option>
    <option value="Human">Человек</option>
    <option value="Orc">Орк</option>
    <option value="Elf">Эльф</option>
</select>
<br>
<input type="number" id="attack" name="attack" placeholder="введите атаку">
<br>
<input type="number" id="defence" name="defence" placeholder="введите защиту">
<br>
<input type="number" id="health" name="health" placeholder="введите здоровье">
<br>
<h1>Выберите персонажа 2</h1>
<select name="character" id="character2">
    <option disabled selected>Выберите расу</option>
    <option value="Human">Человек</option>
    <option value="Orc">Орк</option>
    <option value="Elf">Эльф</option>
</select>
<br>
<input type="number" id="attack2" name="attack2" placeholder="введите атаку">
<br>
<input type="number" id="defence2" name="defence2" placeholder="введите защиту">
<br>
<input type="number" id="health2" name="health2" placeholder="введите здоровье">
<br>
<button id="fight">fight</button>
<script src="js/jquery-3.2.1.min.js"></script>
<script src="js/create.js"></script>
</body>
</html>

